# Generated by Django 4.2.7 on 2024-01-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproject',
            name='project_status',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='AddProjectStatus',
        ),
    ]
