# Generated by Django 4.2.7 on 2024-01-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_createproject_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproject',
            name='project_status',
            field=models.CharField(default='Doing', max_length=50),
        ),
    ]
