# Generated by Django 4.2.7 on 2024-02-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_createproject_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpurchasecomapny',
            name='timestampt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='assignengineer',
            name='timestampt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clientcompanyinfo',
            name='timestampt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='createproject',
            name='timestampt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
