# Generated by Django 4.2.7 on 2024-02-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_createproject_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignengineer',
            name='company_name',
            field=models.CharField(max_length=250),
        ),
    ]
