# Generated by Django 4.2.7 on 2024-02-01 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_assignengineer_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignengineer',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.clientcompanyinfo'),
        ),
    ]
