# Generated by Django 4.2.7 on 2024-02-01 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_assignengineer_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignengineer',
            name='engineer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
