# Generated by Django 4.2.7 on 2024-02-01 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_assignengineer_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignengineer',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.clientcompanyinfo'),
        ),
        migrations.AlterField(
            model_name='assignengineer',
            name='engineer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignengineer',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.addmachinetype'),
        ),
        migrations.AlterField(
            model_name='assignengineer',
            name='travel_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.addtravelby'),
        ),
        migrations.AlterField(
            model_name='createproject',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.clientcompanyinfo'),
        ),
        migrations.AlterField(
            model_name='createproject',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.addmachinetype'),
        ),
    ]
