# Generated by Django 4.2.7 on 2024-02-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_assignengineer_company_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateProject',
        ),
    ]
