# Generated by Django 4.2.7 on 2024-02-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_createproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignengineer',
            name='ending_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignengineer',
            name='work_status',
            field=models.CharField(blank=True, default='Work on Progress', max_length=100, null=True),
        ),
    ]
