# Generated by Django 4.2.7 on 2024-02-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_addmanagers_addreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreport',
            name='ending_time',
            field=models.CharField(max_length=15),
        ),
    ]
