# Generated by Django 4.2.7 on 2024-02-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_addreport_ending_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreport',
            name='total_hours',
            field=models.CharField(max_length=100),
        ),
    ]
