# Generated by Django 4.2.7 on 2024-02-03 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_addreport_total_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_description', models.CharField(blank=True, max_length=500, null=True)),
                ('project_image', models.ImageField(upload_to='project_photos')),
                ('customer_remark', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_status', models.CharField(default='doing', max_length=150)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.assignengineer')),
            ],
        ),
        migrations.DeleteModel(
            name='AddManagers',
        ),
    ]
