# Generated by Django 4.2.7 on 2024-02-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_projectcompletion_delete_addmanagers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcompletion',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_photos'),
        ),
    ]
