# Generated by Django 4.2.7 on 2024-02-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_projectcompletion_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignengineer',
            name='project_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
