# Generated by Django 4.2.7 on 2024-02-05 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_visiblepassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_purpose', models.CharField(max_length=250)),
                ('manager_name', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('work_description', models.CharField(max_length=254)),
                ('category', models.CharField(max_length=254)),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.clientcompanyinfo')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
