# Generated by Django 4.2.7 on 2024-02-05 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_reimbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcompletion',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.assignengineer'),
        ),
    ]
