# Generated by Django 4.2.7 on 2024-02-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_projectcompletion_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignengineer',
            name='machine_type',
            field=models.CharField(max_length=254),
        ),
    ]
