# Generated by Django 4.2.7 on 2024-02-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_assignengineer_machine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='reimbursement_status',
            field=models.CharField(blank=True, default='Pending', max_length=254, null=True),
        ),
    ]
