# Generated by Django 4.2.7 on 2024-02-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_reimbursement_reimbursement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
