# Generated by Django 4.2.7 on 2024-02-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_customuser_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='visible_password',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
