# Generated by Django 4.2.7 on 2024-02-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_customuser_visible_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visiblepassword',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProjectCompletion',
        ),
        migrations.DeleteModel(
            name='VisiblePassword',
        ),
    ]
