# Generated by Django 4.2.7 on 2024-02-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
