# Generated by Django 4.2.7 on 2024-02-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_purchaseorder_serial_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpurchasecomapny',
            old_name='purchase_company_address',
            new_name='purchase_address',
        ),
        migrations.RenameField(
            model_name='addpurchasecomapny',
            old_name='purchase_company_email',
            new_name='purchase_email',
        ),
        migrations.RenameField(
            model_name='addpurchasecomapny',
            old_name='purchase_company_gst',
            new_name='purchase_gst',
        ),
        migrations.RenameField(
            model_name='addpurchasecomapny',
            old_name='purchase_company_name',
            new_name='purchase_name',
        ),
        migrations.RenameField(
            model_name='addpurchasecomapny',
            old_name='purchase_company_phone',
            new_name='purchase_person',
        ),
        migrations.RenameField(
            model_name='addpurchasecomapny',
            old_name='purchase_contact_person',
            new_name='purchase_phone',
        ),
    ]
