# Generated by Django 4.2.7 on 2024-02-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_rename_purchase_company_address_addpurchasecomapny_purchase_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='gst_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='gst_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='subtotal',
            field=models.FloatField(),
        ),
    ]
