# Generated by Django 4.2.7 on 2024-02-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_purchaseorder_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='final_amount',
            field=models.FloatField(),
        ),
    ]
