# Generated by Django 4.2.7 on 2024-02-10 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_purchaseorder_final_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='attendance_status',
            field=models.CharField(blank=True, default='A', max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='UserAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punchin_country', models.CharField(max_length=254)),
                ('punchin_state', models.CharField(max_length=254)),
                ('punchin_location', models.CharField(max_length=500)),
                ('punchin_postcode', models.CharField(max_length=100)),
                ('attendance_date', models.CharField(max_length=254)),
                ('punchin_time', models.TimeField(blank=True, null=True)),
                ('punchout_country', models.CharField(max_length=254)),
                ('punchout_state', models.CharField(max_length=254)),
                ('punchout_location', models.CharField(max_length=500)),
                ('punchout_postcode', models.CharField(max_length=100)),
                ('punchout_time', models.TimeField(blank=True, null=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
