# Generated by Django 4.2.7 on 2024-02-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_customuser_attendance_status_userattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattendance',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
