# Generated by Django 4.2.7 on 2024-02-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_userattendance_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattendance',
            name='punch_status',
            field=models.CharField(blank=True, default='out', max_length=20, null=True),
        ),
    ]
