# Generated by Django 4.2.7 on 2024-02-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_userattendance_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='total_hours',
            field=models.CharField(default='0.00', max_length=200),
        ),
    ]
