# Generated by Django 4.2.7 on 2024-02-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_userattendance_total_hours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userattendance',
            unique_together={('attendance_date', 'engineer')},
        ),
    ]
