# Generated by Django 4.2.7 on 2024-02-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_userattendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='punch_status',
            field=models.CharField(blank=True, default='Absent', max_length=20, null=True),
        ),
    ]
