# Generated by Django 4.2.7 on 2024-02-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_userattendance_punch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_status',
            field=models.CharField(blank=True, default='engineer', max_length=100, null=True),
        ),
    ]
