# Generated by Django 4.2.7 on 2024-02-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_customuser_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_status',
            field=models.CharField(blank=True, default='Engineer', max_length=100, null=True),
        ),
    ]
