# Generated by Django 4.2.7 on 2024-02-13 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_alter_assignengineer_engineer_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignengineer',
            name='engineer_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineer_one_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
