# Generated by Django 4.2.7 on 2024-02-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_attachmentimages_reimbursement_attachment_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='advance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='reimbursement_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
