# Generated by Django 4.2.7 on 2024-02-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_reimbursement_advance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateOrder',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
