# Generated by Django 4.2.7 on 2024-02-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_addunit_delete_addmachinetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='total_cost',
        ),
    ]
