# Generated by Django 4.2.7 on 2024-02-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_remove_customuser_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
