# Generated by Django 4.2.7 on 2024-02-15 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_customuser_total_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_amount', models.IntegerField(blank=True, null=True)),
                ('engineer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.assignengineer')),
            ],
        ),
    ]
