# Generated by Django 4.2.7 on 2024-02-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_advancemoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='attendance_date',
            field=models.DateField(),
        ),
    ]
