# Generated by Django 4.2.7 on 2024-02-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_alter_userattendance_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='attendance_date',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
