# Generated by Django 4.2.7 on 2024-03-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0064_assignengineer_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignengineer",
            name="recived_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="assignengineer",
            name="recived_equipment",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
